server:
  port: 8081
  
spring:  application:
    name: citi-stub
  h2:    console:      path: /h2
      enabled: true
  datasource:    url: jdbc:h2:c:/Users/Vadivelan M/studentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:    show-sql: true
    generate-ddl: true
    properties:      hibernate:
        format_sql: true    hibernate:      ddl-auto: create-drop