    create table IF NOT EXISTS emp_dtls (
       emp_id bigint not null,
        entry_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        last_modify_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        dob timestamp,
        name varchar(75),
        primary key (emp_id)
    );


    create table IF NOT EXISTS emp_addr_dtls (
       emp_id bigint not null,
        address1 varchar(255),
        address2 varchar(255),
        address3 varchar(255),
        pincode bigint,
        remarks clob
    );

    
    create table IF NOT EXISTS std_addr_dtls (
       std_id bigint not null,
        address1 varchar(255),
        address2 varchar(255),
        address3 varchar(255),
        pincode bigint,
        remarks varchar(255),
        primary key (std_id)
    );

    
    create table IF NOT EXISTS std_mark_dtls (
       std_id bigint not null,
        std_mark_details binary(255)
    );

    
    create table IF NOT EXISTS sudentdtls (
       std_id bigint generated by default as identity,
        entry_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        last_modify_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        dob timestamp not null,
        address varchar(250),
        name varchar(75) not null,
        primary key (std_id)
    );

    
 ---   alter table emp_addr_dtls add constraint FKbo0p0u92hba717aimrn69nqt6 foreign key (emp_id) references emp_dtls on delete cascade;

    
--    alter table std_mark_dtls add constraint FKqnftflgwi1rbo8gxjswdyv24b foreign key (std_id) references sudentdtls;